// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACuO7dJZ1H-3bWcA301crCk6KNudVo3LU',
    appId: '1:46132335341:web:7c0c72e3958189ca1872e4',
    messagingSenderId: '46132335341',
    projectId: 'track-my-workout',
    authDomain: 'track-my-workout.firebaseapp.com',
    storageBucket: 'track-my-workout.appspot.com',
    measurementId: 'G-3V1GHP55NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_hmHYv2tGmHlYvaOQFViyjhvARvGWBw',
    appId: '1:46132335341:android:a42faf58778266fc1872e4',
    messagingSenderId: '46132335341',
    projectId: 'track-my-workout',
    storageBucket: 'track-my-workout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYN1mrbh5IRt1UWU_9_VwswyT3gFpPAo',
    appId: '1:46132335341:ios:f06f5a69f7e6fab71872e4',
    messagingSenderId: '46132335341',
    projectId: 'track-my-workout',
    storageBucket: 'track-my-workout.appspot.com',
    androidClientId: '46132335341-5an5pkj4banvnecv0vafkqki19l9q8v5.apps.googleusercontent.com',
    iosClientId: '46132335341-2frrdem6s20u00f8v6jl7mefqehn86q9.apps.googleusercontent.com',
    iosBundleId: 'de.thomas.workoutwatcher.workoutWatcherWeb',
  );
}
